name: 'README Bot'
description: 'AI-powered README maintenance tool that suggests updates based on PR changes'
author: 'README Bot'

branding:
  icon: 'book-open'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: false
    default: ${{ github.token }}
  
  anthropic-api-key:
    description: 'Anthropic Claude API key'
    required: true
  
  format:
    description: 'Output format (github, cli, json)'
    required: false
    default: 'github'
  
  post-comment:
    description: 'Whether to post suggestions as PR comment'
    required: false
    default: 'true'
  
  update-existing:
    description: 'Update existing README-Bot comment instead of creating new ones'
    required: false
    default: 'true'
  
  config-path:
    description: 'Path to custom configuration file'
    required: false
  
  verbose:
    description: 'Enable verbose output'
    required: false
    default: 'false'

outputs:
  needs-update:
    description: 'Whether README needs updates (true/false/unknown)'
  
  suggestion-count:
    description: 'Number of suggestions generated'
  
  comment-url:
    description: 'URL of the posted comment (if applicable)'
  
  error:
    description: 'Error message if analysis failed'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm ci
      shell: bash
      working-directory: ${{ github.action_path }}
    
    - name: Run README Bot
      run: node src/index.js action --format ${{ inputs.format }} ${{ inputs.verbose == 'true' && '--verbose' || '' }}
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
        README_BOT_CONFIG_PATH: ${{ inputs.config-path }}