environment:
  ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"
  GH_APP_ID: "${GH_APP_ID}"
  GH_PRIVATE_KEY: "${GH_PRIVATE_KEY}"
  WEBHOOK_SECRET: "${WEBHOOK_SECRET}"

packages:
  - name: readme-bot
    functions:
      - name: webhook
        runtime: nodejs:18
        web: true
